name: build_website

on:

  push:

    branches:
      - master

permissions:

  contents: write
  deployments: write
  pages: write

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:

      contents: write
      deployments: write
      pages: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pypandoc_binary
        pip install .[doc]

    - name: Setup pandoc
      uses: siacodelabs/setup-pandoc@v1
      with:
        xelatex: true

    - name: Build documentation
      run: |
        sphinx-apidoc -a -e -o docs/source/api atomdb
        sphinx-build -M html docs/source build
        touch build/html/.nojekyll

    - name: Fix documentation permissions
      run: |
        chmod -c -R +rX "build/html/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/html/

    - name: Create soft links
      run: |
        cd website
        ln -s ../notebooks ./examples
        ln -s ../doc/source ./source
        ln -s ../doc/source ./api
        cd ../

    - name: Install Requirements
      run: |
        python3 -m pip install -r website/requirements.txt

    - name: Build Jupyter Book
      run: |
        jupyter-book build ./website/

      # Push the book's HTML to github-pages
      # inspired by https://github.com/orgs/community/discussions/26724
      # only push to gh-pages if the master branch has been updated
    - name: GitHub Pages Action
      # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/_build/html
        publish_branch: gh-pages
        # cname: pyci.qcdevs.org